In [ ]:
import numpy as np

#REEF
#Q1

a=np.random.randint(0,10,(10,10))
print(a)
np.mean(a)

#Q2

a=np.arange(1,16).reshape(3,5).transpose()
b=np.random.randint(0,10,(3,5)).transpose()
b[1,:]=a[1,:]
b[3,:]=a[3,:]
print(a)
print(b)

#Q3

row=int(input('input the number of rows'))
column=int(input('input the number of column'))
a=np.ones([row,column],int)
a[1:row-1,1:column-1]=0
print(a)

#Q4
import math

a=[0.+15*i for i in range(7)]
a=np.array(a)
print(a)
b=np.sin(a*math.pi/180)
c=np.cos(a*math.pi/180)
d=np.tan(a*math.pi/180)
print(b)
print(c)
print(d)
e=np.arcsin(b)*180/math.pi
f=np.arccos(c)*180/math.pi
g=np.arctan(d)*180/math.pi
print(e)
print(f)
print(g)

#Q5

x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
y=[]
for i in range(len(x)-1):
    y.append(x[i+1]-x[i])
print(y)

#Q7

a=np.random.rand(10)*10
a_ave=np.mean(a)
b=0.
for i in range(len(a)):
    b+=(a[i]-a_ave)**2
sqr_exp=b/len(a)
std_exp=np.sqrt(sqr_exp)
print(std_exp)
print(np.std(a))


#Tagaras

import numpy as np
import random
#Exerrcise 1
m = np.random.rand(10,10)*10
np.mean(m)
#Exercise 2
a=np.arange(1,16).reshape(3,5).transpose()
b = np.array([a[1],a[3]])
#Exercise 4
angles = np.arange(0,7)*15*np.pi/180.0
sin = np.sin(angles)
cos = np.cos(angles)
tan = np.tan(angles)
arcsin = np.arcsin(sin)
arccos = np.arccos(cos)
arctan = np.arctan(tan)
#print(angles, arcsin)
#Exercise 7
def deviation(array):
    #return np.sqrt(np.sum(array-np.mean(array))/array.size)
    return np.sqrt(np.sum((array-np.mean(array))**2)/array.size)
test = np.arange(1,5)
print(test,deviation(test), np.std(test))

# Vasile

#Q7

import random
x = np.random.randint(1, 20, 10)
sum(x)
def std_dev(a):
    a_bar = sum(a)/len(a)
    ss = 0
    for i in range(len(a)):
        ss += (a[i] - a_bar)**2
    return np.sqrt(ss/len(a)) 
print(std_dev(x))
print(np.std(x))

#Q6


x = np.loadtxt('sample.txt')
y = np.histogram(x)
avgs = np.zeros(len(y[1])-1)
len(y[1])
#iterate through the edges
for i in range(len(y[1])-1):
    avgs = (y[1][i] + y[1][i+1])/2
    print('bin average: ', avgs, ';', 'bin count: ', y[0][i])

    
#Q5

x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
diffs = np.zeros(len(x))
for i in range(len(x)-1):
    diffs[i] = x[i]-x[i+1]
diffs

#Q4
degrees = np.arange(0, 105, 15)
print(degrees)
#sin, cos, tan
import math
sine = np.zeros(len(degrees))
cose = np.zeros(len(degrees))
tang = np.zeros(len(degrees))
for i in range(len(degrees)):
    sine[i] = math.sin(degrees[i])
    cose[i] = math.cos(degrees[i])
    tang[i] = math.tan(degrees[i])
#inverses
inv_sin = np.zeros(len(degrees))
inv_cose = np.zeros(len(degrees))
inv_tan = np.zeros(len(degrees))
for i in range(len(degrees)):
    inv_sin[i] = math.asin(sine[i])
    inv_cose[i] = math.acos(cose[i])
    inv_tan[i] = math.atan(tang[i])
print(inv_sin)
print(inv_cose)
print(inv_tan)

#Q3

def two_d_array(n):
    a = np.ones((n, n))
    for i in range(1, len(a)-1):
        for j in range(1, len(a)-1):
            a[i, j] = 0
    return a
two_d_array(6)

#Q2


a=np.arange(1,16).reshape(3,5).transpose()
a
b=a[(1,3),:]
b
c= np.ones((5, 5))
len(c)


#Hongrui He

#Q7
Array = [10,10,23,44,55,66,77,99]
def stdCompute(InputList):
    import numpy as np
    InputArray = np.array(InputList)
    Average = np.mean(InputArray)
    DiffArray = np.zeros(InputArray.shape)
    for Index in range(len(InputArray)):
        DiffArray[Index] = InputArray[Index] - Average
    DiffArray = DiffArray ** 2
    SumVariant = np.sum(DiffArray)
    sigma = ( SumVariant / len(InputArray) ) ** (1/2)
    return sigma
SigmaWrite = stdCompute(Array)
SigmaIntrinsic = np.std(Array)
Diff = abs(SigmaWrite - SigmaIntrinsic)
print(Diff)

#Q6

Data = np.loadtxt('NumpyData.txt')
Counts,HisArray = np.histogram(Data)
for Index in range(len(Counts)):
    print('Bin Center {} with counts {}'.format(HisArray[Index],Counts[Index]))
    

#Q5

x = np.array([1, -1, 2, 5, 8, 4, 10, 12, 3])
Diff = np.diff(x)
print(Diff)


#Q4

DegreeArray = np.linspace(0,90,7)
RadiansArray = np.radians(DegreeArray)
SineArray = np.sin(RadiansArray)
CosineArray = np.cos(RadiansArray)
TangentArray = np.tan(RadiansArray)
aSineArray = np.degrees(np.arcsin(SineArray))
aCosineArray = np.degrees(np.arccos(CosineArray))
aTangentArray = np.degrees(np.arctan(TangentArray))
DiffSine = abs(aSineArray - DegreeArray)
print(DiffSine)
DiffCosine = abs(aCosineArray - DegreeArray)
print(DiffCosine)
DiffTangent = abs(aTangentArray - DegreeArray)
print(DiffTangent)

# Arjun virk

#Author: Arjun Virk
#Date: March 8th
#This is for Numpy-Exercises: Q7
import numpy as np
import random
N = 10 #Set number of elements in array
a=np.random.random_sample(10)*N #Create random array
a_avg = np.mean(a) #calculate mean of array
sum_of_squares = np.empty((10,1)) #Set up array for sum of squares
for ii in range(len(sum_of_squares)): #Loop over elements
    sum_of_squares[ii] = (a[ii] - a_avg)**2 #Calculate the differce
sum_of_squares_total = np.sum(sum_of_squares) #Calculate the sum of squares
sum_of_squares_total = sum_of_squares_total/N #Divide by total number of elements
a_std = np.sqrt(sum_of_squares_total) #calculate standard deviation
a_std_2 = np.std(a) #Find stadnard deviation using numpy program
print(a_std) #Print value using our own code
print(a_std_2) #Print valye from built-in function


[[7 8 7 6 7 7 6 3 6 5]
 [3 9 5 1 7 5 9 2 1 3]
 [1 9 4 8 8 3 0 6 7 3]
 [6 8 1 0 0 5 7 0 8 1]
 [5 0 4 3 0 2 5 3 7 5]
 [5 0 0 2 7 6 9 9 7 7]
 [9 8 3 6 0 6 4 4 7 4]
 [7 2 1 0 8 3 4 2 6 3]
 [5 8 8 7 7 4 5 0 4 2]
 [7 4 9 9 1 6 1 6 4 4]]
[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]
[[ 5  8  3]
 [ 2  7 12]
 [ 2  0  1]
 [ 4  9 14]
 [ 1  5  0]]
